"""initial unified schema

Revision ID: 4f958357504d
Revises:
Create Date: 2026-06-06 21:00:06.587166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = "4f958357504d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=False),
        sa.Column("points_reward", sa.Float(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("condition_type", sa.String(length=64), nullable=False),
        sa.Column("condition_value", sa.Integer(), nullable=True),
        sa.Column("hidden", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    with op.batch_alter_table("achievements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_achievements_category"), ["category"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_achievements_condition_type"), ["condition_type"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("gemini_api_key", sa.String(length=255), nullable=True),
        sa.Column("api_key_validated", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("identicon_value", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            "idx_users_email_unique", ["email"], unique=True, sqlite_where=text("email IS NOT NULL")
        )

    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("feedback", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["username"], ["users.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_feedback_username"), ["username"], unique=False)

    op.create_table(
        "point_transactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("is_expired", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["username"], ["users.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("point_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_point_transactions_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_point_transactions_is_expired"), ["is_expired"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_point_transactions_source"), ["source"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_point_transactions_username"), ["username"], unique=False
        )

    op.create_table(
        "prompt_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("prompt_id", sa.String(length=64), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["username"], ["users.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "username", "prompt_id", "version_number", name="uq_prompt_versions_user_pid_v"
        ),
    )
    with op.batch_alter_table("prompt_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_prompt_versions_prompt_id"), ["prompt_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_prompt_versions_username"), ["username"], unique=False)

    op.create_table(
        "prompts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("random_val", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["username"], ["users.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", "random_val", name="uq_prompts_username_random"),
    )
    with op.batch_alter_table("prompts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prompts_random_val"), ["random_val"], unique=False)
        batch_op.create_index(batch_op.f("ix_prompts_username"), ["username"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_active", sa.DateTime(), nullable=True),
        sa.Column("revoked", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["username"], ["users.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_username"), ["username"], unique=False)

    op.create_table(
        "shared_prompts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("random_val", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["owner"], ["users.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("random_val"),
    )
    with op.batch_alter_table("shared_prompts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shared_prompts_owner"), ["owner"], unique=False)

    op.create_table(
        "user_achievements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("achievement_id", sa.Integer(), nullable=False),
        sa.Column("unlocked_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["achievement_id"], ["achievements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["username"], ["users.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", "achievement_id", name="uq_user_achievements_user_ach"),
    )
    with op.batch_alter_table("user_achievements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_achievements_achievement_id"), ["achievement_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_user_achievements_username"), ["username"], unique=False
        )

    op.create_table(
        "user_logins",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("login_date", sa.Date(), nullable=False),
        sa.Column("points_awarded", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["username"], ["users.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", "login_date", name="uq_user_logins_username_date"),
    )
    with op.batch_alter_table("user_logins", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_logins_username"), ["username"], unique=False)

    op.create_table(
        "point_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=16), nullable=False),
        sa.Column("points_before", sa.Float(), nullable=False),
        sa.Column("points_after", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["transaction_id"], ["point_transactions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["username"], ["users.username"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("point_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_point_history_transaction_id"), ["transaction_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_point_history_username"), ["username"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("point_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_point_history_username"))
        batch_op.drop_index(batch_op.f("ix_point_history_transaction_id"))

    op.drop_table("point_history")
    with op.batch_alter_table("user_logins", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_logins_username"))

    op.drop_table("user_logins")
    with op.batch_alter_table("user_achievements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_achievements_username"))
        batch_op.drop_index(batch_op.f("ix_user_achievements_achievement_id"))

    op.drop_table("user_achievements")
    with op.batch_alter_table("shared_prompts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shared_prompts_owner"))

    op.drop_table("shared_prompts")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_username"))

    op.drop_table("sessions")
    with op.batch_alter_table("prompts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prompts_username"))
        batch_op.drop_index(batch_op.f("ix_prompts_random_val"))

    op.drop_table("prompts")
    with op.batch_alter_table("prompt_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prompt_versions_username"))
        batch_op.drop_index(batch_op.f("ix_prompt_versions_prompt_id"))

    op.drop_table("prompt_versions")
    with op.batch_alter_table("point_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_point_transactions_username"))
        batch_op.drop_index(batch_op.f("ix_point_transactions_source"))
        batch_op.drop_index(batch_op.f("ix_point_transactions_is_expired"))
        batch_op.drop_index(batch_op.f("ix_point_transactions_expires_at"))

    op.drop_table("point_transactions")
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_username"))

    op.drop_table("feedback")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index("idx_users_email_unique", sqlite_where=text("email IS NOT NULL"))

    op.drop_table("users")
    with op.batch_alter_table("achievements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_achievements_condition_type"))
        batch_op.drop_index(batch_op.f("ix_achievements_category"))

    op.drop_table("achievements")
    # ### end Alembic commands ###
